### ISSUE TITLE
手势bug

### ISSUE THREAD

**Issue by FanYuanBo888** [choiceyou/FWSideMenu#2]
默认 在centerVC上可以使用侧滑手势 打开侧边栏，但当我在centerVC上push一个新的VC后，我测滑新的VC并不能返回上一个界面，而是直接打开了侧边栏。

**Comment by choiceyou** [comment]
侧滑开关操作有开放，我已经加入demo中了，你可以参考下

**Comment by FanYuanBo888** [comment]
OK 谢谢

发自我的 iPhone

**Comment by coderiding** [comment]
就算按你demo的操作，还是会把系统的手势返回给拦截了

**Comment by choiceyou** [comment]
嗨，2.0.4版本已经支持了边缘滑动手势，解决了困扰大家的手势冲突问题
